# Generated by Django 3.1.7 on 2021-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftshop',
            name='birth_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='giftshop',
            name='citizen_id',
            field=models.IntegerField(default=405),
        ),
    ]
