# Generated by Django 3.1.7 on 2021-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0003_auto_20210609_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftshop',
            name='citizen_id',
            field=models.IntegerField(default=252),
        ),
        migrations.AlterField(
            model_name='giftshop',
            name='gender',
            field=models.CharField(max_length=7),
        ),
    ]
