# Generated by Django 3.1.7 on 2021-06-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0005_auto_20210609_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftshop',
            name='citizen_id',
            field=models.IntegerField(default=742),
        ),
        migrations.CreateModel(
            name='Birthdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsons.giftshop')),
            ],
        ),
    ]
