# Generated by Django 3.1.7 on 2021-06-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0006_auto_20210610_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdays',
            name='month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftshop',
            name='citizen_id',
            field=models.IntegerField(default=906),
        ),
    ]
