# Generated by Django 3.1.7 on 2021-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0007_auto_20210610_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftshop',
            name='citizen_id',
            field=models.IntegerField(default=437),
        ),
        migrations.DeleteModel(
            name='Birthdays',
        ),
    ]
